// SPDX-License-Identifier: MIT

pragma solidity ^0.8.9;

/**
 * @title  SBINFT market non-native asset transfer protocol
 */
interface ISBT {
  /** event などを定義 */

  function updateBaseTokenURI(string memory _uri) external;

  /**
   * @dev Creates a new token for `to`. Its token ID will be automatically
   * assigned (and available on the emitted {IERC721-Transfer} event), and the token
   * URI autogenerated based on the base URI passed at construction.
   *
   * See {ERC721-_mint}.
   *
   * Requirements:
   *
   * - the caller must have the `MINTER_ROLE`.
   */
  function mint(address to) external;

  function bulkMint(address[] calldata tos) external;

  function burn(uint256 tokenId) external;

  function bulkBurn(uint256[] calldata tokenIds) external;

  function boardingMembersExist() external returns (bool);

  function boardingMembers() external returns (address[] memory);

  /**
   * @dev Resolve Kaname Protocol DID from the board which tokenId is `tokenId`.
   */
  function did(uint256 tokenId) external view returns (string memory);

  /**
   * @dev Returns Kaname Protocol DID spec's schema.
   */
  function didSchema() external pure returns (string memory);

  /**
   * @dev Returns Kaname Protocol DID spec's namespace corresponding to the boards.
   */
  function didNamespace() external view returns (string memory);

  /**
   * @dev Returns Kaname Protocol DID spec's member.
   */
  function didMember(address member) external view returns (string memory);
}
