// SPDX-License-Identifier: MIT

pragma solidity ^0.8.9;

/**
 * @title  SBINFT market non-native asset transfer protocol
 */
interface ISBT {
    

    /** event などを定義 */

    function updateBaseTokenURI(string memory _uri) external;

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_mint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     */
    function mint(address to) external;

    function Bulkmint(address[] calldata tos) external;

    function burn(uint256 tokenId) external;

    function Bulkburn(uint256[] calldata tokenIds) external;

}