// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

/**
 * @title Board SBT interface
 */
interface ISBT {
  /** event などを定義 */

  /**
   * @dev Creates a new token for `to`. Its token ID will be automatically
   * assigned (and available on the emitted {IERC721-Transfer} event), and the token
   * URI autogenerated based on the base URI passed at construction.
   *
   * See {ERC721-_mint}.
   *
   * Requirements:
   *
   * - the caller must have the `MINTER_ROLE`.
   */
  function mint(address to) external;

  function bulkMint(address[] calldata tos) external;

  function burn(uint256 tokenId) external;

  function bulkBurn(uint256[] calldata tokenIds) external;

  function boardingMembersExist() external returns (bool);

  function boardingMembers() external returns (address[] memory);
}
